//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Git SHA: 73b15936467f1778e7b8cc614681f64c06b60841 - master")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.3.0 73b15936467f1778e7b8cc614681f64c06b60841/master")]


