//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Git SHA: 023456645d6c017eea4dbeaa9d9f1b6c8cdf25b9 - master")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.4.0")]


